In [1]:
import pandas as pd

df = pd.read_csv(r"C:\online_retail\data\raw\online_retail_II.csv")

In [2]:
df.assign(
    InvoiceType=df["Invoice"].astype(str).str[0]
).query(
    "InvoiceType in ['C', 'A']"
).groupby("InvoiceType")["Country"].nunique()

InvoiceType
A     1
C    36
Name: Country, dtype: int64

In [3]:
price_by_invoice_type = (
    df.assign(
        InvoiceType=df["Invoice"].astype(str).str[0]
    )
    .groupby("InvoiceType")
    .agg(
        Total_Rows=("Price", "size"),
        Zero_Price=("Price", lambda x: (x == 0).sum()),
        Negative_Price=("Price", lambda x: (x < 0).sum()),
        Positive_Price=("Price", lambda x: (x > 0).sum())
    )
    .reset_index()
)

price_by_invoice_type

  InvoiceType  Total_Rows  Zero_Price  Negative_Price  Positive_Price
0           4      108489        1108               0          107381
1           5      939382        5094               0          934288
2           A           6           0               5               1
3           C       19494           0               0           19494

In [4]:
c_data = df[
    df["Invoice"].astype(str).str.startswith("C")
].copy()

c_data["Amount"] = c_data["Quantity"] * c_data["Price"]

c_data[["Invoice", "Quantity", "Price", "Amount"]].head(20)

     Invoice  Quantity  Price  Amount
178  C489449       -12   2.95  -35.40
179  C489449        -6   1.65   -9.90
180  C489449        -4   4.25  -17.00
181  C489449        -6   2.10  -12.60
182  C489449       -12   2.95  -35.40
183  C489449       -12   1.25  -15.00
184  C489449       -12   1.25  -15.00
185  C489449       -24   0.85  -20.40
186  C489449       -12   2.95  -35.40
196  C489459        -3   4.25  -12.75
197  C489459        -3   4.25  -12.75
198  C489459        -3   4.25  -12.75
199  C489459        -3   4.25  -12.75
200  C489459        -3   4.25  -12.75
201  C489459        -3   4.25  -12.75
202  C489459        -3   4.25  -12.75
203  C489459        -3   3.75  -11.25
204  C489459        -3   3.75  -11.25
205  C489459        -3   3.75  -11.25
206  C489459        -3   2.10   -6.30

In [5]:
c_data["Amount"].describe()

count     19494.000000
mean        -78.314756
std        1459.635817
min     -168469.600000
25%         -17.850000
50%          -8.950000
75%          -3.750000
max         373.570000
Name: Amount, dtype: float64

Potential/expected revenue that was lost because the sale was cancelled.

In [6]:
print("Negative amounts:", (c_data["Amount"] < 0).sum())
print("Zero amounts:", (c_data["Amount"] == 0).sum())
print("Positive amounts:", (c_data["Amount"] > 0).sum())

Negative amounts: 19493
Zero amounts: 0
Positive amounts: 1

In [7]:
print("Negative quantity:", (c_data["Quantity"] < 0).sum())
print("Zero quantity:", (c_data["Quantity"] == 0).sum())
print("Positive quantity:", (c_data["Quantity"] > 0).sum())

Negative quantity: 19493
Zero quantity: 0
Positive quantity: 1

In [8]:
c_data[c_data["Amount"] > 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Amount
76799,C496350,M,Manual,1,2010-02-01 08:24:00,373.57,NaN,United Kingdom,373.57