In [1]:
import pandas as pd

df = pd.read_csv(r"C:\online_retail\data\raw\online_retail_II.csv")

In [2]:
df["Amount"] = df["Quantity"] * df["Price"]

df[["Invoice", "StockCode", "Description", "Quantity", "Price", "Amount"]].head(20)

,Invoice,StockCode,Description,Quantity,Price,Amount
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,6.95,83.40
1,489434,79323P,PINK CHERRY LIGHTS,12,6.75,81.00
2,489434,79323W,WHITE CHERRY LIGHTS,12,6.75,81.00
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2.10,100.80
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,1.25,30.00
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,1.65,39.60
6,489434,21871,SAVE THE PLANET MUG,24,1.25,30.00
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,5.95,59.50
8,489435,22350,CAT BOWL,12,2.55,30.60
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,3.75,45.00
10,489435,22195,HEART MEASURING SPOONS LARGE,24,1.65,39.60
11,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2.55,30.60
12,489436,48173C,DOOR MAT BLACK FLOCK,10,5.95,59.50
13,489436,21755,LOVE BUILDING BLOCK WORD,18,5.45,98.10
14,489436,21754,HOME BUILDING BLOCK WORD,3,5.95,17.85
15,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,1.69,27.04
16,489436,22119,PEACE WOODEN BLOCK LETTERS,3,6.95,20.85
17,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,1.45,17.40
18,489436,22296,HEART IVORY TRELLIS LARGE,12,1.65,19.80
19,489436,22295,HEART FILIGREE DOVE LARGE,12,1.65,19.80

In [3]:
df["Amount"].describe()

count    1.067371e+06
mean     1.806987e+01
std      2.924202e+02
min     -1.684696e+05
25%      3.750000e+00
50%      9.900000e+00
75%      1.770000e+01
max      1.684696e+05
Name: Amount, dtype: float64

In [4]:
df.nlargest(20, "Amount")[
    ["Invoice", "StockCode", "Description",
     "Quantity", "Price", "Amount", "Customer ID", "Country"]
]

,Invoice,StockCode,Description,Quantity,Price,Amount,Customer ID,Country
1065882,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2.08,168469.60,16446.0,United Kingdom
587080,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,1.04,77183.60,12346.0,United Kingdom
748132,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50,38970.00,15098.0,United Kingdom
241827,512771,M,Manual,1,25111.09,25111.09,NaN,United Kingdom
432176,530715,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,9360,1.69,15818.40,15838.0,United Kingdom
517955,537632,AMAZONFEE,AMAZON FEE,1,13541.33,13541.33,NaN,United Kingdom
540478,537632,AMAZONFEE,AMAZON FEE,1,13541.33,13541.33,NaN,United Kingdom
825443,A563185,B,Adjust bad debt,1,11062.06,11062.06,NaN,United Kingdom
135013,502263,M,Manual,1,10953.50,10953.50,12918.0,United Kingdom
135015,502265,M,Manual,1,10953.50,10953.50,NaN,United Kingdom
342147,522796,M,Manual,1,10468.80,10468.80,NaN,United Kingdom
358639,524159,M,Manual,1,10468.80,10468.80,14063.0,United Kingdom
372834,525399,M,Manual,1,10468.80,10468.80,NaN,United Kingdom
74356,496115,M,Manual,1,8985.60,8985.60,17949.0,United Kingdom
228042,511465,15044A,PINK PAPER PARASOL,3500,2.55,8925.00,18008.0,United Kingdom
698843,551697,POST,POSTAGE,1,8142.75,8142.75,16029.0,United Kingdom
873786,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,5.06,7144.72,17450.0,United Kingdom
374227,525473,M,Manual,1,7044.79,7044.79,NaN,United Kingdom
129903,501766,M,Manual,1,6958.17,6958.17,15760.0,Norway
129987,501768,M,Manual,1,6958.17,6958.17,15760.0,Norway

In [5]:
df.nsmallest(20, "Amount")[
    ["Invoice", "StockCode", "Description",
     "Quantity", "Price", "Amount", "Customer ID", "Country"]
]

,Invoice,StockCode,Description,Quantity,Price,Amount,Customer ID,Country
1065883,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2.08,-168469.60,16446.0,United Kingdom
587085,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,1.04,-77183.60,12346.0,United Kingdom
179403,A506401,B,Adjust bad debt,1,-53594.36,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,-44031.79,-44031.79,NaN,United Kingdom
748142,C556445,M,Manual,-1,38970.00,-38970.00,15098.0,United Kingdom
403472,A528059,B,Adjust bad debt,1,-38925.87,-38925.87,NaN,United Kingdom
241824,C512770,M,Manual,-1,25111.09,-25111.09,17399.0,United Kingdom
320581,C520667,BANK CHARGES,Bank Charges,-1,18910.69,-18910.69,NaN,United Kingdom
1050063,C580605,AMAZONFEE,AMAZON FEE,-1,17836.46,-17836.46,NaN,United Kingdom
569163,C540117,AMAZONFEE,AMAZON FEE,-1,16888.02,-16888.02,NaN,United Kingdom
569164,C540118,AMAZONFEE,AMAZON FEE,-1,16453.71,-16453.71,NaN,United Kingdom
517953,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,-13541.33,NaN,United Kingdom
519294,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,-13541.33,NaN,United Kingdom
540477,C537630,AMAZONFEE,AMAZON FEE,-1,13541.33,-13541.33,NaN,United Kingdom
541817,C537651,AMAZONFEE,AMAZON FEE,-1,13541.33,-13541.33,NaN,United Kingdom
519170,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,-13474.79,NaN,United Kingdom
541463,C537644,AMAZONFEE,AMAZON FEE,-1,13474.79,-13474.79,NaN,United Kingdom
1050062,C580604,AMAZONFEE,AMAZON FEE,-1,11586.50,-11586.50,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,-11062.06,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,-11062.06,-11062.06,NaN,United Kingdom

In [6]:
df.assign(
    InvoiceType=df["Invoice"].astype(str).str[0]
).query(
    "Amount < 0"
).groupby("InvoiceType")["Amount"].agg(
    ["count", "sum", "min", "max"]
)

             count         sum        min       max
InvoiceType
A                5  -158676.14  -53594.36 -11062.06
C            19493 -1527041.43 -168469.60     -0.12

In [7]:
df["Amount"].sum()

np.float64(19287250.568)

In [8]:
df["Amount"].gt(0).sum()
df["Amount"].lt(0).sum()

np.int64(19498)

In [9]:
df.groupby(
    df["Invoice"].astype(str).str[0]
)["Amount"].agg(["count", "sum", "mean", "min", "max"])

          count           sum          mean        min        max
Invoice
4        108489  2.119408e+06     19.535698      -0.00    8985.60
5        939382  1.884212e+07     20.058000      -0.00  168469.60
A             6 -1.476141e+05 -24602.346667  -53594.36   11062.06
C         19494 -1.526668e+06    -78.314756 -168469.60     373.57

In [10]:
df.groupby("Description")["Amount"].sum().sort_values(ascending=False).head(20)

Description
REGENCY CAKESTAND 3 TIER               327813.65
DOTCOM POSTAGE                         322647.47
WHITE HANGING HEART T-LIGHT HOLDER     257533.90
JUMBO BAG RED RETROSPOT                148800.64
PARTY BUNTING                          147948.50
ASSORTED COLOUR BIRD ORNAMENT          131413.85
PAPER CHAIN KIT 50'S CHRISTMAS         121662.14
POSTAGE                                112341.00
CHILLI LIGHTS                           84854.16
ROTATING SILVER ANGELS T-LIGHT HLDR     73814.72
BLACK RECORD COVER FRAME                69247.18
JUMBO BAG STRAWBERRY                    69053.65
RABBIT NIGHT LIGHT                      66756.59
HOT WATER BOTTLE TEA AND SYMPATHY       62722.55
WOOD BLACK BOARD ANT WHITE FINISH       62517.02
JUMBO STORAGE BAG SUKI                  61574.65
PAPER CHAIN KIT VINTAGE CHRISTMAS       60533.44
VINTAGE UNION JACK BUNTING              60124.54
CHOCOLATE HOT WATER BOTTLE              60075.64
EDWARDIAN PARASOL NATURAL               59846.48
Name: Amount, dtype: float64

In [11]:
df[df["Amount"] < 0].groupby("Description")["Amount"].sum().sort_values().head(20)

Description
Manual                               -423886.17
AMAZON FEE                           -294772.71
PAPER CRAFT , LITTLE BIRDIE          -168469.60
Adjust bad debt                      -158676.14
MEDIUM CERAMIC TOP STORAGE JAR        -77479.64
Bank Charges                          -33997.91
REGENCY CAKESTAND 3 TIER              -16749.60
POSTAGE                               -15256.42
Discount                              -13882.43
WHITE HANGING HEART T-LIGHT HOLDER     -9389.65
CRUK Commission                        -7933.43
COLOUR GLASS. STAR T-LIGHT HOLDER      -6976.41
FAIRY CAKE FLANNEL ASSORTED COLOUR     -6614.37
WHITE CHERRY LIGHTS                    -6331.30
SAMPLES                                -6202.65
SET/4 WHITE RETRO STORAGE CUBES        -5187.65
PANTRY CHOPPING BOARD                  -4803.06
DOORMAT FAIRY CAKE                     -4650.20
TEA TIME PARTY BUNTING                 -4490.50
RED RETROSPOT CAKE STAND               -4405.25
Name: Amount, dtype: float64